#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION lib/version.py`)
ELECTRUM_XGOX_VERSION=${VERSION_STRING[2]}
ELECTRUM_XGOX_VERSION=${ELECTRUM_XGOX_VERSION#\'}
ELECTRUM_XGOX_VERSION=${ELECTRUM_XGOX_VERSION%\'}
DOTS=`echo $ELECTRUM_XGOX_VERSION |  grep -o "\." | wc -l`
if [[ $DOTS -lt 3 ]]; then
    ELECTRUM_XGOX_APK_VERSION=$ELECTRUM_XGOX_VERSION.0
else
    ELECTRUM_XGOX_APK_VERSION=$ELECTRUM_XGOX_VERSION
fi
export ELECTRUM_XGOX_VERSION
export ELECTRUM_XGOX_APK_VERSION
